### ISSUE TITLE
Overly strict error handling for "unknown key"

### ISSUE THREAD

**Issue by eli-schwartz** [Morganamilo/go-srcinfo#2]
Recently, pacman-git has added support for the global keyword "b2sums", and this library will error out when it sees a .SRCINFO that contains the result -- something which I am beginning to do, since makepkg itself does not care whether I add an integity algorithm it doesn't support, so it is fully backwards compatible.

This means that the `yay` AUR helper fails to work when it sees the package.

There are two issues at play here:
- The library does not know that there are new keys, and thus does not add this data to its internal .SRCINFO representation
- The library considers new key names that match the expected file format, to be an error, and does not appear to have an API to reduce the strictness

I'm unsure whether it is a good idea to do this sort of error checking. ;) It's essentially saying the implementation must be evolved in parallel with makepkg and (potentially) receive constant updates in order to remain relevant. Downstream consumers, like yay, will therefore run into errors when they have not yet adapted to new versions of the specification.

**Comment by eli-schwartz** [comment]
See also https://github.com/Jguer/yay/issues/926

**Comment by Morganamilo** [comment]
Yeah I meant to remove that a long time ago but never got around to it. In fact I wrote a rust version of this lib and made sure to not include the unknown key error.

A lot of the original strictness comes from #1. But given that all my patches are now merged half of the strictness checks are kind of redundant now anyway.

**Comment by Morganamilo** [comment]
Fixed and added b2sums.
